# Generated by Django 5.1.6 on 2025-02-10 23:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('HOME', 'Home'), ('AUTO', 'Auto'), ('HEALTH', 'Health'), ('TRAVEL', 'Travel'), ('LIFE', 'Life')], max_length=20)),
                ('expiry_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 2, 10))])),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
